### ISSUE TITLE
Error: suppa_split_file.R Input_file must contain samplesheet samples.

### ISSUE THREAD

**Issue by ludirm93** [nf-core/rnasplice#122]
https://github.com/nf-core/rnasplice/blob/f70bbce27cbade36f993a7e39fa6e574fc4c6d3a/bin/suppa_split_file.R#L75

This error occurred for me when input sample-sheet had sample names with "-" in them. 
the workflow ran fine till tximport but below function converted "-" to "." as er default R behaviour

input_file <- read.csv(input_file, sep="\t", header=TRUE)

need to include check.names = F in the read.csv function.

**Comment by jma1991** [comment]
Hi @ludirm93 

Thanks for reporting this issue. I have fixed it in the latest version 1.0.3. Keep an eye out for the official release, should be by end of day.

**Comment by IanCodes** [comment]
I had this error, however it was not due to '-' in the sample names.  It appeared to be caused by the sample names being too long.  The longest was 14 characters.  The only other special characters in the names were '_'.  Replacing the names with those up to to four characters long avoided the error.

`ERROR ~ Error executing process > 'NFCORE_RNASPLICE:RNASPLICE:SUPPA_SALMON:SPLIT_FILES_TPM (suppa_tpm.txt)'

Caused by:
  Process `NFCORE_RNASPLICE:RNASPLICE:SUPPA_SALMON:SPLIT_FILES_TPM (suppa_tpm.txt)` terminated with an error exit status (1)

Command executed:

  suppa_split_file.R \
      suppa_tpm.txt \
      samplesheet_fastqs_minus.csv \
      .tpm \
      false \
  
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNASPLICE:RNASPLICE:SUPPA_SALMON:SPLIT_FILES_TPM":
      r-base: $(echo $(R --version 2>&1) | sed 's/^.*R version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: Skipping mount /usr/local/singularity-ce-3.11.2/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Error: suppa_split_file.R Input_file must contain samplesheet samples.
  Execution halted
  INFO:    Cleaning up image...

Work dir:
  /<PATH>/work/ae/fc9b5a6e9323150b1b522a92fa23c1

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
`
